#!/usr/bin/env node

var fs = require('fs')
  , path = require('path')
  , minimist = require('minimist')

// getting cli arguments
var argv = minimist(process.argv)

// loading the dictionary
var dictionary = loadDictionary()

// loading the file with the content to be replaced
var content = loadToReplace()

// doing the actual replacing
content = replace(dictionary, content)

// writing result to stdout
stdout(content)

function loadDictionary ()  {
  var filepath = argv['dictionary'] ||
    path.join(process.cwd(), './dictionary.json')
  return require(filepath.toString())
}

function loadToReplace () {
  var filepath = argv['to-replace']
  if (!filepath) {
      console.error('You should provide the filepath to the original content \
to be replaced with the "--to-replace" argument.')
      process.exit(1)
  }
  return fs.readFileSync(filepath.toString(), 'utf8')
}

function replace (dictionary, content) {
  for (var key in dictionary)
    content = content.replace(key, dictionary[key], 'g')
  return content
}

function stdout (content) {
  process.stdout.write(content)
}
