#!/usr/bin/env node

var fs = require('fs')
  , path = require('path')
  , args = require('./args')

var toReplacePath = args.next('--to-replace')
if (!toReplacePath) {
    console.error('You should provide the filepath to the original content to be replaced with the \
\'--to-replace\' argument.')
    process.exit(1)
}

var dictionaryPath = args.next('--dictionary') || path.join(process.cwd(), './dictionary.json')

var dictionary = require(dictionaryPath)
var content = fs.readFileSync(toReplacePath, 'utf8')

for (var key in dictionary) {
    content = content.replace(key, dictionary[key], 'g')
}

process.stdout.write(content)
